name: admpfr CI (macOS)

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  macos:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Alire
        uses: alire-project/setup-alire@v1

      - name: Set up env
        run: |
          ls -al alire_install
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew install mpfr
          pip3 install e3-testsuite

      - name: Build and test admpfr
        run: |
          export LIBRARY_PATH=/usr/local/lib
          export C_INCLUDE_PATH=/usr/local/include
          alr build
          eval `alr printenv`
          ./testsuite/testsuite.py --failure-exit-code=1
