name: admpfr CI

on:
  push:
    branches:
    - main
    - main/**
  pull_request:
    branches:
    - main
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  macos:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Alire
        uses: alire-project/setup-alire@v1

      - name: Set up env
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew install mpfr
          brew install pipx
          pipx install e3-testsuite

      - name: Build and test admpfr
        continue-on-error: true # remove when https://github.com/actions/runner-images/issues/8642 is fixed
        run: |
          export LIBRARY_PATH=/usr/local/lib
          export C_INCLUDE_PATH=/usr/local/include
          alr build
          alr exec -- ./testsuite/testsuite.py -E --failure-exit-code=1

  ubuntu:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Alire
        uses: alire-project/setup-alire@v1

      - name: Set up env
        run: |
          sudo apt install libmpfr-dev
          pip3 install e3-testsuite

      - name: Build and test admpfr
        run: |
          alr build
          alr exec -- ./testsuite/testsuite.py -E --failure-exit-code=1

  windows:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up git
        run: |
          git config --global core.autocrlf false

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Alire
        uses: alire-project/setup-alire@v1

      - name: Set up env
        run: |
          C:\Users\runneradmin\.cache\alire\msys64\usr\bin\pacman --noconfirm -S mingw-w64-x86_64-mpfr
          # Install e3-core and e3-testsuite from source to benefit from the rlimit bugfix
          # but stick to 6f597b3 until Python 3.10+ is available, see https://github.com/AdaCore/e3-core/commit/c021846c7c62248771b26ef4061836d3352ce0f7,
          # `strict` argument in call to `realpath` is available only after Python 3.10.
          pip install git+https://github.com/AdaCore/e3-core.git@6f597b3 
          pip install git+https://github.com/AdaCore/e3-testsuite.git@master

      - name: Build and test admpfr
        run: |
          alr build
          alr exec -- python.exe .\testsuite\testsuite.py -E --failure-exit-code=1
