name: admpfr CI (macOS)

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  macos:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up env
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew install mpfr
          wget https://github.com/alire-project/alire/releases/download/v1.1.2/alr-1.1.2-bin-x86_64-macos.zip
          unzip alr-1.1.2-bin-x86_64-macos.zip
          bin/alr get gprbuild
          bin/alr get gnat_native
          pip3 install e3-testsuite

      - name: Build and test admpfr
        run: |
          export LIBRARY_PATH=/usr/local/lib
          cd gnat_native*/ && export PATH=$PATH:$PWD/bin && cd -
          cd gprbuild*/ && export PATH=$PATH:$PWD/bin && cd -
          ./testsuite/testsuite.py
